apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1

spec:
  replicas: 2
  selector:
    matchLabels:
       app: myapp 
  template:
      metadata:       #Dictionary
        name: myapp-pod
        labels:
          app: myapp   #Key-value pairs
      spec:
        containers:     #List object
        - name: myapp
          image: kaleshaaks.azurecr.io/dotnet:latest
          ports:
            - containerPort: 5205

