apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: kaleshaaks.azurecr.io/dotnet:latest
    ports:
    - containerPort: 5205
  imagePullSecrets:
  - name: dotnetsecret